import { Noto_Sans, Roboto_Flex } from "next/font/google";
import "./globals.css";
import NavModal from "@/components/nav/NavModal";

const noto_Sans = Noto_Sans({
  weight: ["500", "700"],
  variable: "--noto_sans",
  subsets: ["latin"],
});
const roboto_Flex = Roboto_Flex({
  weight: ["100", "300", "400", "600"],
  variable: "--roboto_flex",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${noto_Sans.variable} ${roboto_Flex.variable}`}>
      <body>
        {children}
        <NavModal />
      </body>
    </html>
  );
}
